# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ab1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ab2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reav', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('media', models.DecimalField(decimal_places=2, max_digits=6)),
                ('faltas', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('max_faltas', models.IntegerField()),
                ('conceito', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
