# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materias_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='notas',
            new_name='dados',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='nome',
        ),
    ]
